### ISSUE TITLE
Query on attributes related to F & B specs

### ISSUE THREAD

**Issue by VidyaGF** [Open-network-for-digital-commerce/ONDC-Live#1]
The ondc namespace attributes like  /ondc-cancellable, /ondc-returnable are only included  for Retail. But how do buyer apps know that orders/items  in F & B are non-cancellable, non-returnable?
Referring to the below specs :
https://app.swaggerhub.com/apis/ONDC/ONDC-Protocol-Food-and-Beverage/1.0.0-draft
https://app.swaggerhub.com/apis/ONDC/ONDC-Protocol-Hyperlocal/1.0.0-draft

**Comment by BLR-0118** [comment]
@VidyaGF - pls send your updated list of attributes to add to f&b

**Comment by VidyaGF** [comment]
ok , I will provide by tomorrow EOD

**Comment by BLR-0118** [comment]
@VidyaGF - pls provide the updated list of attributes [here](https://github.com/Open-network-for-digital-commerce/ONDC-Protocol-Specs/issues)

**Comment by VidyaGF** [comment]
These attributes will be required for now for F & B segment. We may need to add more ,if any attribute is missed out later.
"./ondc-returnable"
"./ondc-cancellable"
"./ondc-time_to_ship"

**Comment by BLR-0118** [comment]
Added this to ONDC-Protocol-Specs repo
