### ISSUE TITLE
Error in initializeOrder api

### ISSUE THREAD

**Issue by bizom-utkarsh** [Open-network-for-digital-commerce/ONDC-Live#4]
When the frontend is calling initializeOrder api, the response as seen in developer tools says  : BPP returned error
However, when I check my logs, I am not even receiving the request
Here is the response to the initializeOrder api that I captured from developer tools :

```
{
  "status": 500,
  "response": {
    "req": {
      "method": "POST",
      "url": "https://qa.api.box.beckn.org/bap/client/v1/initialize_order",
      "data": {
        "context": {
          "transaction_id": "4311a5b1-6f4d-47ae-9748-61dfaf052aef"
        },
        "message": {
          "items": [
            {
              "id": "10",
              "quantity": {
                "count": 1
              },
              "bpp_id": "stagingapigateway.bizom.in/ondc",
              "provider": {
                "id": "1513",
                "locations": [
                  null
                ]
              }
            }
          ],
          "billing_info": {
            "address": {
              "door": " doddanekundi",
              "country": "IND",
              "city": "Bengaluru",
              "street": "bangalore",
              "area_code": "560100",
              "state": "Karnataka",
              "building": "10"
            },
            "phone": "9999999999",
            "name": "utkarsh",
            "email": ""
          },
          "delivery_info": {
            "type": "HOME-DELIVERY",
            "name": "utkarsh",
            "phone": "9999999999",
            "email": "",
            "location": {
              "address": {
                "door": " doddanekundi",
                "country": "IND",
                "city": "Bengaluru",
                "street": "bangalore",
                "area_code": "560100",
                "state": "Karnataka",
                "building": "10"
              },
              "gps": "12.9063433,77.5856825"
            }
          }
        }
      },
      "headers": {
        "content-type": "application/json"
      }
    },
    "header": {
      "date": "Wed, 23 Mar 2022 21:30:39 GMT",
      "content-type": "application/json",
      "content-length": "436",
      "connection": "close",
      "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
      "expires": "0",
      "pragma": "no-cache",
      "vary": "Origin, Access-Control-Request-Method, Access-Control-Request-Headers",
      "x-content-type-options": "nosniff",
      "x-frame-options": "DENY",
      "x-krakend": "Version 1.4.1",
      "x-krakend-completed": "false",
      "x-xss-protection": "1; mode=block"
    },
    "status": 500,
    "text": "{\"context\":{\"domain\":\"nic2004:52110\",\"country\":\"IND\",\"city\":\"std:080\",\"action\":\"init\",\"core_version\":\"0.9.1\",\"bap_id\":\"box.beckn.org\",\"bap_uri\":\"https://qa.api.box.beckn.org/bap/protocol/v1\",\"transaction_id\":\"4311a5b1-6f4d-47ae-9748-61dfaf052aef\",\"message_id\":\"2f9e7465-7d33-4c83-8b7f-6d732ea7549b\",\"timestamp\":\"2022-03-23T21:30:39.074233Z\"},\"message\":{\"ack\":{\"status\":\"NACK\"}},\"error\":{\"code\":\"BAP_011\",\"message\":\"BPP returned error\"}}"
  }
}
```
**Steps to recreate**
1. Go to https://qa.box.beckn.org/
2. Enter location as bangalore
3. Enter chocolate in search bar (see image 1)
4. You will get a listing Distiman by Bizom (see image 2)
5. Add it to cart (see image 3)
6. Click on Proceed
7. Enter shipping address (see image 4)
8. Click on Proceed
9. You will see the error page (see image 5)

![1](https://user-images.githubusercontent.com/102280577/159855818-ddf0fd2f-1286-446e-8bed-6cc190d0aaa8.png)
![2](https://user-images.githubusercontent.com/102280577/159855825-33b2d31c-723a-4c48-82be-6d0d668622b8.png)
![3](https://user-images.githubusercontent.com/102280577/159855829-fdb73cee-f97f-43de-ab83-d3669aca7df4.png)
![4](https://user-images.githubusercontent.com/102280577/159855834-f39562a3-7b9c-4782-bb17-5e874bc4133d.png)
![Screenshot from 2022-03-24 12-00-24](https://user-images.githubusercontent.com/102280577/159856096-ac559aeb-cd09-412c-b923-4bc2f831ca7c.png)

**After this Rajat from ONDC team replied the following :** 
Just noticed that in our select request we are not sending provider and provider_location  info  like mentioned below , This location information is required in init api calls due to which right now in UI side they are sending us null object as location.
```
"provider": {
                "id": "453678",
                "descriptor": {
                    "name": "Grocery Retail",
                    "short_desc": "Grocery Retail Product.",
                    "images": [
                        ""
                    ]
                },
                "locations": [
                    {
                        "id": "el",
                        "gps": "12.891704, 77.576873",
                        "address": {
                            "door": "",
                            "name": "Address Name",
                            "building": "West side",
                            "street": "lsts 354537",
                            "locality": "",
                            "state": "Bangalore",
                            "country": "IND",
                            "area_code": "160002"
                        },
                        "station_code": "160002",
                        "city": {
                            "name": "Bangalore",
                            "code": "Bangalore"
                        },
                        "country": {
                            "name": "IND",
                            "code": "IN"
                        }
                    }
                ]
            },
            "provider_location": {
                "id": "el"
            }
```
**After this, following was my reply and I am waiting for further response from ONDC team**
I am actually not sure, what I should do from my end to fix this. I added the keys provider and providerLocation as part of on_select response but I am still getting the same error in initializeOrder api

**Comment by BLR-0118** [comment]
@techframewirk - pls request Ujjwal's help on this

**Comment by bizom-utkarsh** [comment]
I was trying to reproduce the issue and i have observed some changes.

As can be seen above in **image 4**, after click on **Proceed** button,

Instead of getting the error page as in **image 5**, now i am getting a loader as can be seen in below image
![image](https://user-images.githubusercontent.com/102280577/160752528-06f43c3f-316a-4575-9413-1ea4e671be1f.png)
and the **onInitializeOrder** Api is continuously getting called.

When I checked the logs on my end, on sending the response to **on_init** endpoint,  I am getting a **500 INTERNAL SERVER ERROR** as can be seen below
![image](https://user-images.githubusercontent.com/102280577/160752884-b1e1aacb-ae08-46c9-8dcb-326cc71e787d.png)

**Comment by BLR-0118** [comment]
@techframewirk pls request Ujjwal's help on this

**Comment by BLR-0118** [comment]
@bizom-utkarsh - pls check if this is fixed

**Comment by bizom-utkarsh** [comment]
This is not resolved.
I am still receiving **500 INTERNAL_SERVER_ERROR** on calling the **on_init** api
As per Ujjwal's comment, I have added the key **location_id** in the **on_search** response

**Comment by BLR-0118** [comment]
@techframewirk - request Ujjwal's help on this

**Comment by BLR-0118** [comment]
@bizom-utkarsh - many fixes deployed for gateway & reference buyer app over last few days. Can you please check this once again & post screenshot here if not working?

**Comment by bizom-utkarsh** [comment]
BAP is down right now
![image](https://user-images.githubusercontent.com/102280577/161325816-4ce31428-3c57-4c3f-9673-3f101985a9dc.png)

**Comment by bizom-utkarsh** [comment]
**UPDATE:**
nirmal nr from ondc team showed me the error in my payload due to which I was receiving 500 status code.
I fixed it and now this api is working fine.
Will close this issue.
