### ISSUE TITLE
Items sent by on_search response are not displayed on https://qa.box.beckn.org/

### ISSUE THREAD

**Issue by VidyaGF** [Open-network-for-digital-commerce/ONDC-Live#7]
We are getting a search request from the https://qa.box.beckn.org/  to our BPP and we are sending the on_search response back . (When we do a F12 ,we are able to see the sent items at client layer api response) But we are not able to see the response . We see "Something went wrong " error

**Comment by BLR-0118** [comment]
@VidyaGF - is this fixed?

**Comment by BLR-0118** [comment]
@VidyaGF - many fixes deployed for gateway & reference buyer app over last few days. Can you please check this once again & post screenshot here if not working?

**Comment by dhiraj-nsdl** [comment]
@VidyaGF We have deployed fix for 400 bad request issues. There is an issue at Buyer side where we have marked Nirmal and Rajat to look into it.

**Comment by sujitrs** [comment]
@VidyaGF Can you please check and confirm with Nirmal and Rajat ? So that this can be marked as closed.

**Comment by VidyaGF** [comment]
This can be closed.
