### ISSUE TITLE
Search through Beckn ref app not reaching our service.

### ISSUE THREAD

**Issue by Manoj-Patkar** [Open-network-for-digital-commerce/ONDC-Live#8]
We have on-boarded our BPP into the Sandbox registry, but still not able to search products from the reference beckn app. The search in the app is not hitting our BPP as verified from the logs. The search works fine with the postman.

Please can you help us with this? We are using self signed certs for our BPP let us know if this causes any issues?

Registry resp
[
    {
        "br_id": 146,
        "subscriber_id": "[storeez.co.in](http://storeez.co.in/)",
        "subscriber_url": "https://35.207.205.153/v1/ondc",
        "type": "BPP",
        "domain": "nic2004:52110",
        "city": "std:080",
        "country": "IND",
        "signing_public_key": "fH5muGx7TBLulOqhZq5Ma1jNbTTI9PAC2b2iU4CHQqc=",
        "encr_public_key": "ebU3HWf8dyX6s6FSqDWEjlt+MtBf3M7D1EOpzGvB9yE=",
        "valid_from": "2021-10-26T16:00:48.072Z",
        "valid_until": "2024-11-26T16:00:48.072Z",
        "status": "SUBSCRIBED",
        "created": "2022-02-07T10:57:44.057Z",
        "updated": "2022-02-07T10:57:44.057Z",
        "ukId": "146"
    }
]

The same one working through postman
![image](https://user-images.githubusercontent.com/20676778/160980932-f591cc21-eaf9-4322-ad43-602cbff72ebe.png)

**Comment by BLR-0118** [comment]
@dhiraj-nsdl - what's the problem?

**Comment by dhiraj-nsdl** [comment]
@BLR-0118 @Manoj-Patkar BPP is using self signed certificate. We need to import the self signed public certificate of BPP.

**Comment by BLR-0118** [comment]
@Manoj-Patkar - you need to have your self-signed certificates manually imported into the cert store of gateway. Please contact @dhiraj-nsdl to process this
